[palette]
Rosewater = ""
Flamingo = ""
Pink = ""
Mauve = ""
Red = ""
Maroon = ""
Peach = ""
Yellow = ""
Green = ""
Teal = ""
Sky = ""
Sapphire = ""
Blue = ""
Lavender = ""
Text = ""
"Subtext 1" = ""
"Subtext 0" = ""
"Overlay 2" = ""
"Overlay 1" = ""
"Overlay 0" = ""
"Surface 2" = ""
"Surface 1" = ""
"Surface 0" = ""
"Base" = ""
"Mantle" = ""
"Crust" = ""
