[palette]
Rosewater = "#f2d5cf"
Flamingo = "#eebebe"
Pink = "#f4b8e4"
Mauve = "#ca9ee6"
Red = "#e78284"
Maroon = "#ea999c"
Peach = "#ef9f76"
Yellow = "#e5c890"
Green = "#a6d189"
Teal = "#81c8be"
Sky = "#99d1db"
Sapphire = "#85c1dc"
Blue = "#8caaee"
Lavender = "#babbf1"
Text = "#c6d0f5"
"Subtext 1" = "#b5bfe2"
"Subtext 0" = "#a5adce"
"Overlay 2" = "#949cbb"
"Overlay 1" = "#838ba7"
"Overlay 0" = "#737994"
"Surface 2" = "#626880"
"Surface 1" = "#51576d"
"Surface 0" = "#414559"
"Base" = "#303446"
"Mantle" = "#292c3c"
"Crust" = "#232634"
