[palette]
Rosewater = "#f4dbd6"
Flamingo = "#f0c6c6"
Pink = "#f5bde6"
Mauve = "#c6a0f6"
Red = "#ed8796"
Maroon = "#ee99a0"
Peach = "#f5a97f"
Yellow = "#eed49f"
Green = "#a6da95"
Teal = "#8bd5ca"
Sky = "#91d7e3"
Sapphire = "#7dc4e4"
Blue = "#8aadf4"
Lavender = "#b7bdf8"
Text = "#cad3f5"
"Subtext 1" = "#b8c0e0"
"Subtext 0" = "#a5adcb"
"Overlay 2" = "#939ab7"
"Overlay 1" = "#8087a2"
"Overlay 0" = "#6e738d"
"Surface 2" = "#5b6078"
"Surface 1" = "#494d64"
"Surface 0" = "#363a4f"
"Base" = "#24273a"
"Mantle" = "#1e2030"
"Crust" = "#181926"
